#!/bin/ksh
#
# Generate the individual test files for each of the data files
#
for i in 1h_ipnat_parse_???_v4.data; do
	j=${i%_v4.data}
	k=${j#1h_ipnat_parse_}
	sed -e s/XXX/$k/ 1h_ipnat_rf_XXX_v4_sh > 1h_ipnat_rf_${k}_v4.sh
done

for i in 1h_ipf_parse_???_v4.data; do
	j=${i%_v4.data}
	k=${j#1h_ipf_parse_}
	sed -e s/XXX/$k/ 1h_ipf_rf_XXX_v4_sh > 1h_ipf_rf_${k}_v4.sh
	sed -e s/XXX/$k/ 1h_ipf_parse_XXX_v4_sh > 1h_ipf_parse_${k}_v4.sh
done

for i in 001 012 014; do
	sed -e s/XXX/$i/ 1h_ipf_flush_XXX_v4_sh > 1h_ipf_flush_${i}_v4.sh
done

for i in 001 002 004 005 100; do
	sed -e s/XXX/$i/ 1h_ipnat_flush_XXX_v4_sh > 1h_ipnat_flush_${i}_v4.sh
done
