#!/bin/sh
if [ x${BASEDIR} = x -o x${BASEDIR} = x/ ] ; then
	rem_drv pfil
else
	rem_drv -b ${BASEDIR:-/} pfil
fi
egrep -v 'name=pfil' /etc/devlink.tab > /etc/devlink.tab.new
mv /etc/devlink.tab /etc/devlink.tab.bak
cp -p /etc/devlink.tab.bak /etc/devlink.tab
cp /etc/devlink.tab.new /etc/devlink.tab
/usr/sbin/devlinks
if [ -d /usr/ucb -a -f /usr/ucb/ucblinks ] ; then
	/usr/ucb/ucblinks
fi
exit 0
