#!/bin/sh

cd ${BASEDIR:-/}
cd kernel/drv

if [ -f pfil -a ! -f pfil.dist ] ; then
	mv pfil pfil.dist
fi

for i in *; do
	if [ -d $i -a -f $i/pfil -a ! -f $i/pfil.dist ] ; then
		mv $i/pfil $i/pfil.dist
	fi
done
exit 0
