#!/bin/ksh

cdir=$(pwd)
cd /export/home/darrenr/ipf51/test/regress/

for f in in[0-9] in1[0-9][0-9]; do
	j=${f#in}
	n=$(printf '%03d' $j)
	cat >${cdir}/1h_ipnat_parse_${n}_v4.sh <<__EOF
gen_ipf_conf() {
	return 0;
}

gen_ipnat_conf() {
	cat <<__EOF__
__EOF
	cat $f >> ${cdir}/1h_ipnat_parse_${n}_v4.sh
	cat >>${cdir}/1h_ipnat_parse_${n}_v4.sh <<__EOF
__EOF__
	return 0;
}

gen_ippool_conf() {
	return 1;
}

do_test() {
	validate_loaded_ipf_conf
	return \$?
}

do_tune() {
	return 0;
}

do_verify() {
	return 0;
}
__EOF
done
