#!/bin/ksh

cdir=$(pwd)
cd /export/home/darrenr/ipf51/test/regress/

for f in i[0-9] i[0-9][0-9]; do
	j=${f#i}
	n=$(printf '%03d' $j)
	cat >${cdir}/1h_ipf_parse_$n.sh <<__EOF
gen_ipf_conf() {
	cat <<__EOF__
__EOF
	cat $f >> ${cdir}/1h_ipf_parse_$n.sh
	cat >>${cdir}/1h_ipf_parse_$n.sh <<__EOF
__EOF__
	return 0;
}

gen_ipnat_conf() {
	return 1;
}

gen_ippool_conf() {
	return 1;
}

do_test() {
	validate_loaded_ipf_conf
	return \$?
}

do_tune() {
	return 0;
}

do_verify() {
	return 0;
}
__EOF
done
