#!/bin/sh
testitem=$1
TESTMODE=$2

if [ ${TESTMODE} != user ] ; then
	exit 0
fi

. ./ipflib.sh

test_init
set $args
. ./setup_test.sh
echo "${todo}...";
input=`expr ${todo} : 'bpf-\(.*\)'`
/bin/cp /dev/null ${results}
( while read rule; do
	echo "$rule" | ../ipftest -Rbr - -i input/$input >> ${results} &
	back=$!
	wait $back
	test_end_leak $?
	next_core
	echo "--------" >> ${results};
done ) < ${regress}
check_results
exit $status
