#!/bin/sh
testitem=$1
TESTMODE=$2

. ./ipflib.sh

test_init
set $args
format=$2

# multiple rules at the same time

. ./setup_test.sh
echo "${todo}...";

set_core $todo 1

if [ ${TESTMODE} = kern ] ; then
	../ipf -D
	../ipf -E
fi
../ipftest -M ${TESTMODE} -F $format $4 -Rbr ${regress} -i ${input} > ${results} &
back=$!
wait $back
status=$?
if [ ${TESTMODE} = kern ] ; then
	../ipf -D
fi
test_end_leak $status
echo "--------" >> ${results}

check_results
exit $status
