#!/bin/sh
testitem=$1
TESTMODE=$2

. ./ipflib.sh

test_init
# $1, etc, are all changed now
thistest=$1
format=$2
output=$3

. ./setup_test.sh

args=""
while [ "$4" != "" ] ; do
	case $4 in
	-*)
		args="$args $4"
		;;
	*)
		args="$args -T $4"
		;;
	esac
	shift
done
if [ ${TESTMODE} = kern ] ; then
	args="-M kern $args"
else
	args="$args"

fi
echo "${todo}...";
/bin/cp /dev/null ${results}
( while read rule; do
	if [ ${TESTMODE} = kern ] ; then
		../ipf -D
		../ipf -E
	fi
	echo "$rule" | ../ipftest ${args} -F $format -Rbr - \
				  -i ${input} ${tuning} >> ${results} &
	back=$!
	wait $back
	status=$?
	if [ ${TESTMODE} = kern ] ; then
		../ipf -D
	fi
	test_end_leak $status
	echo "--------" >> ${results}
	next_core
done ) < ${regress}
check_results
exit $status
