#!/bin/sh
testitem=$1
TESTMODE=$2
todo=`expr ${testitem} : '.*\/\(.*\)$'`
resdir=`expr ${testitem} : '\(.*\)\/.*$'`
args=`awk "/^${todo} / { print; } " test.format`
set $args

if [ ${TESTMODE} != user ] ; then
	exit 0
fi

. ./setup_test.sh
echo "${todo}...";
/bin/cp /dev/null ${results}
case $3 in
ipf)
	../ipf -Rnvf ${regress} 2>/dev/null > ${results}
	status=$?
	;;
ipftest)
	../ipftest -D -r ${regress} -i /dev/null > ${results}
	status=$?
	;;
esac
if [ $status -eq 0 ] ; then
	cmp ${expected} ${results}
	status=$?
fi
if [ $status = 0 ] ; then
	$TOUCH ${resdir}/${todo}
fi
exit $status
