#!/bin/sh
testitem=$1
TESTMODE=$2

if [ ${TESTMODE} != user ] ; then
	exit 0
fi

. ./ipflib.sh

test_init
set $args

. ./setup_test.sh

echo "${todo}...";
/bin/cp /dev/null ${results}
case $3 in
ipf)
	../ipf -Rnvf ${regress} 2>/dev/null > ${results}
	status=$?
	;;
ipftest)
	../ipftest -D -r ${regress} -i /dev/null > ${results}
	status=$?
	;;
esac
if [ $status -eq 0 ] ; then
	check_results $status
fi
exit $status
