#!/bin/sh
testitem=$1
TESTMODE=$2
todo=`expr ${testitem} : '.*\/\(.*\)$'`
resdir=`expr ${testitem} : '\(.*\)\/.*$'`
args=`awk "/^${todo} / { print; } " test.format`
set $args

if [ ${TESTMODE} != user ] ; then
	exit 0
fi

. ./setup_test.sh
echo "${todo}...";
/bin/cp /dev/null results/$1
../ipnat -Rnvf ${regress} 2>/dev/null > ${results}
cmp ${expected} ${results}
status=$?
if [ $status = 0 ] ; then
	$TOUCH ${resdir}/${todo}
fi
exit $status
