#!/bin/sh
testitem=$1
TESTMODE=$2

. ./ipflib.sh

test_init

if [ ${TESTMODE} != user ] ; then
	exit 0
fi

. ./setup_test.sh

echo "${todo}...";
/bin/cp /dev/null results/$1
../ipnat -Rnvf ${regress} 2>/dev/null > ${results}

check_results
exit $status
