#!/bin/sh
testitem=$1
TESTMODE=$2

if [ ${TESTMODE} != user ] ; then
	exit 0
fi

. ./ipflib.sh

test_init
set $args
. ./setup_test.sh
echo "${todo}...";
/bin/cp /dev/null ${results}
../ippool -f ${regress} -nRv 2>/dev/null > ${results}
check_results
exit $status
