#!/bin/sh
testitem=$1
TESTMODE=$2

. ./ipflib.sh

format=$2
. ./setup_test.sh
echo "${todo}...";
/bin/cp /dev/null ${results}
../ipftest -6 -r /dev/null -i /dev/null >/dev/null 2>&1
if [ $? -ne 0 ] ; then
	echo "skipping IPv6 tests"
	$TOUCH $1
	exit 0
fi
( while read rule; do
	if [ ${TESTMODE} = kern ] ; then
		../ipf -D
		../ipf -E
	fi
	echo "$rule" | ../ipftest -M ${TESTMODE} -F ${format} -6br - \
				  -i ${input} >> ${results} &
	back=$!
	wait $back
	status=$?
	if [ ${TESTMODE} = kern ] ; then
		../ipf -D
	fi
	test_end_leak $status
	echo "--------" >> ${results}
	next_core
done ) < ${regress}
check_results
exit $status
