#!/bin/sh
testitem=$1
todo=`expr ${testitem} : '.*\/\(.*\)$'`
resdir=`expr ${testitem} : '\(.*\)\/.*$'`
args=`awk "/^${todo} / { print; } " test.format`
set $args
results=${resdir}/results/${todo}

format=$2
mkdir -p results
if [ -f /usr/ucb/touch ] ; then
	TOUCH=/usr/ucb/touch
else
	if [ -f /usr/bin/touch ] ; then
		TOUCH=/usr/bin/touch
	else
		if [ -f /bin/touch ] ; then
			TOUCH=/bin/touch
		fi
	fi
fi
echo "$1...";

case `uname -s` in
OSF1)
	GMT=:
	;;
*)
	GMT=GMT
	;;
esac

/bin/cp /dev/null ${results}
/bin/cp /dev/null ${results}.b

( while read rule; do
	echo $rule >> ${results}
	echo $rule | ../ipftest -br - -F $format -i input/$1 -l logout > /dev/null
	if [ $? -ne 0 ] ; then
		/bin/rm -f logout
		exit 1
	fi
	TZ=$GMT ../ipmon -P /dev/null -f logout >> ${results}
        echo "--------" >> ${results}
	TZ=$GMT ../ipmon -P /dev/null -bf logout >> ${results}.b
        echo "--------" >> ${results}.b
done ) < regress/${todo}
../ipftest -br regress/${todo} -F $format -i input/${todo} -l logout > /dev/null
TZ=$GMT ../ipmon -P /dev/null -f logout >> ${results}
echo "--------" >> ${results}
TZ=$GMT ../ipmon -P /dev/null -bf logout >> ${results}.b
echo "--------" >> ${results}.b

cmp expected/${todo} ${results}
status=$?
if [ $status -ne 0 ] ; then
	exit $status
fi
cmp expected/${todo}.b ${results}.b
status=$?
if [ $status -ne 0 ] ; then
	exit $status
fi
/bin/rm -f logout
$TOUCH ${resdir}/${todo}
exit 0
