#!/bin/sh
testitem=$1
TESTMODE=$2

. ./ipflib.sh

test_init

name=$1

if [ $3 = hex ] ; then
	format="-xF $2"
else
	format="-F $2"
fi
if [ "$4" != "" ] ; then
	case $4 in
	-*)
		format="$4 $format"
		;;
	*)
		format="-T $4 $format"
		;;
	esac
fi
echo "${todo}...";
. ./setup_test.sh
/bin/cp /dev/null ${results}
( while read rule; do
	if [ ${TESTMODE} = kern ] ; then
		../ipf -D
		../ipf -E
	fi
	echo "$rule" | ../ipftest $format -M ${TESTMODE} -DRbN - \
				  -i ${input} >> ${results} &
	back=$!
	wait $back
	status=$?
	if [ ${TESTMODE} = kern ] ; then
		../ipf -D
	fi
	test_end_leak $status
	echo "-------------------------------" >> ${results}
	next_core
done ) < ${regress}
check_results
exit $status
