#!/bin/sh
testitem=$1
TESTMODE=$2

if [ ${TESTMODE} != user ] ; then
	exit 0
fi

. ./ipflib.sh

test_init
set $args

. ./setup_test.sh

/bin/rm -f ${testitem}

echo "${todo}...";
/bin/cp /dev/null ${results}
if [ ${TESTMODE} = kern ] ; then
	../ipf -D
	../ipf -E
fi
if [ -f regress/${todo}.pool -a -f "${regress_ipf}" ] ; then
	../ipftest -RD -b -P regress/${todo}.pool -r ${regress_ipf} \
		   -i ${input} >> ${results} &
elif [ -f regress/${todo}.pool -a -f "${regress_nat}" ] ; then
	../ipftest -RD -b -P regress/${todo}.pool -N ${regress_nat} \
		   -i ${input} >> ${results} &
else
	../ipftest -RD -b -r ${regress_ipf} -i ${input} >> ${results} &
fi
back=$!
wait $back
status=$?
if [ ${TESTMODE} = kern ] ; then
	../ipf -D
fi
test_end_leak $status
echo "-------------------------------" >> ${results}
check_results
exit $status
