.TH DNS-PROXY 5
.SH NAME
dns-proxy.conf \- configuration file for dns-proxy
.SH DESCRIPTION
.PP
The \fBdns-proxy.conf\fP file is used by \fBdns-proxy\fP to define how
it should receive packets and how it should respond to those it receives.
.SH CONFIG LINES
.PP
Each of the valid configuration lines for \fBdns-proxy.conf\fP is given
below.
.SS port
The \fBport\fP line defines a local port upon which \fBdns-proxy\fP should
wait for DNS queries to arrive via UDP.  Each port line must have a
\fIname\fP, \fIlocaladdress\fP and \fIportnumber\fP.  The role of each
of these is described below.
.TP
.I name
The \fIname\fP given to a \fBport\fP rule is arbitrary.  It is used
for joining together an inbound processing port with a set of \fBacl\fP
rules (see below.)
.TP
.I localaddress
The \fIlocaladdress\fP defines which IP address will be used as the
local endpoint at which queries are expected to be received.
.TP
.I portnumber
The \fIportnumber\fP specifies which UDP port will be opened at the
address given by \fIlocaladdress\fP for receipt of DNS packets.
.TP
.I transparent\fP
Specifying this option on the end of a \fBport\fP rule is an explicit
indication of whether or not packets are being redirected to this
\fIportnumber\fP using \fBipnat\fP's \fIrdr\fP rules.  If it is set
to \fBon\fP, \fBdns-proxy\fP will attempt to get the original
destination from IPFilter in order to forward it to the correct
destination.
.PP
Two examples of what a port line looks like are:
.nf

port locals 10.22.113.1 53;
port redirs 10.22.113.1 5053 { transparent on; };
.fi
.SS forwarders
The \fBforwarders\fP line defines which IP addresses to use for resolving
queries sent from the inside.  The list is used in round-robin fasion.
Retransmits of the exact same query from an internal host will always
go to the same forwarder.
.PP
There are no rules on where a \fBforwarders\fP line must be in relation
to any other lines in the \fBdns-proxy.conf\fP file.
.PP
\fBNOTE:\fP If a packets is received on a port set for use in transparent
mode then the list of hosts specified in the forwarders list is ignored.
.PP
An example of how this configuration is used is as follows:
.nf

forwarders { 127.0.0.1; };
forwarders { 127.0.0.1, 10.1.1.1; };
.fi
.SS acl
The \fBacl\fP line is used to define which \fIquestions\fP and
\fIanswers\fP are to be allowed through this proxy.  An \fBacl\fP line
\fBMUST\fP be specified after the name \fBport\fP listed in it.
In the example below, it would be assumed that there had been a
\fBport\fP rule earlier int the \fBdns-proxy.conf\fP file that
defined what \fIlocals\fP was.
.PP
Each \fBacl\fP rule is comprised of a \fIhostlist\fP, \fIportname\fP
and set of statements deciding which questions/answers to allow or
deny.
.PP
The \fIhostlist\fP is a comma seperated list of IP addresses plus
a netmask, specified in CIDR notation.  For convenience, it the
word \fBall\fP is recognised as an alias for "0.0.0.0/0".  An \fBacl\fP
rule may specify just one address or many.
.PP
The actions that can be taken on a matching name are:
.TP
.I allow
Allow the DNS packet through
.TP
.I block
Silently discard the DNS packet
.TP
.I reject
Retrun an error to the querier, indicating that the name does not exist.
.PP
When specifying a name with one of \fBallow\fP, \fBblock\fP or \fBreject\fP,
it is possible to have it start with either a '*' or '.'.  The only wildcard
recognised is a leading '*' at the front of a name.
.PP
Some example lines are as follows:
.nf

acl some { source(10.1.1.1/32,10.2.2.0/24); port (locals);
	   policy { allow .com, .net; }; };
acl many { source(*); port (locals);
	   policy { block .microsoft.com; block *cnn.com; }; };
.fi
.SS modify
The \fBquery\fP line is used to do explicit matching and policy enforcement
depending on the contents of the DNS query.  These lines are \fBoptional\fP.
The \fBquery\fP line allows you to match on the following DNS fields:
.TP
.I recursion
.TP
.I keep
.TP
.I strip
.TP
.I clean
.PP
.nf

modify default question { acl(*); recursion preserve; keep ($safe);
    strip($bad); clean (*);};
.fi
.SS forward
A \fBforward\fP line joins together a set of \fIacl\fP rules with a set
of \fIforwarders\fP that have been defined previously.
.PP
.nf

forward { acl (local); to (localhost); };
forward { acl (*); to (default); };
.fi
.SH FILES
/etc/dns-proxy.conf
.SH SEE ALSO
dns-proxy(8)
.SH BUGS
.PP
If you find any, please send email to me at darrenr@pobox.com
